// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmVIX6L81WZrM3boj8Ps3UavaZoE0YNQ',
    appId: '1:353174574270:web:a946df02f92b8e53843aef',
    messagingSenderId: '353174574270',
    projectId: 'eikhatib',
    authDomain: 'eikhatib.firebaseapp.com',
    storageBucket: 'eikhatib.firebasestorage.app',
    measurementId: 'G-YZHG54Q4W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbTLK8tuQCJTZ0ppbObDLr0QvOAW91CU0',
    appId: '1:353174574270:android:59f73bb68e6b11d4843aef',
    messagingSenderId: '353174574270',
    projectId: 'eikhatib',
    storageBucket: 'eikhatib.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIpH4VNMevt-K_78qDu-6EgN_hvsGHtF4',
    appId: '1:353174574270:ios:2922dd0addfe70a8843aef',
    messagingSenderId: '353174574270',
    projectId: 'eikhatib',
    storageBucket: 'eikhatib.firebasestorage.app',
    iosBundleId: 'com.eikhatib.eikhatib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIpH4VNMevt-K_78qDu-6EgN_hvsGHtF4',
    appId: '1:353174574270:ios:361a0e35b2e2cce4843aef',
    messagingSenderId: '353174574270',
    projectId: 'eikhatib',
    storageBucket: 'eikhatib.firebasestorage.app',
    iosBundleId: 'com.example.eikhatib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVmVIX6L81WZrM3boj8Ps3UavaZoE0YNQ',
    appId: '1:353174574270:web:2fe8257dc1e5415d843aef',
    messagingSenderId: '353174574270',
    projectId: 'eikhatib',
    authDomain: 'eikhatib.firebaseapp.com',
    storageBucket: 'eikhatib.firebasestorage.app',
    measurementId: 'G-TPW2RXFQQ3',
  );
}
